### ISSUE TITLE
Can't compile on Ubuntu 20.04.4

### ISSUE THREAD

**Issue by ztjuh** [kaltura/nginx-srt-module#18]
I'm getting a error while compiling. 

````
./nginx-srt-module/src/ngx_srt_connection.c:1943:9: error: implicit declaration of function ‘srt_bind_acquire’ [-Werror=implicit-function-declaration]
 1943 |     if (srt_bind_acquire(ss, ls->fd) != 0) {
      |         ^~~~~~~~~~~~~~~~
cc1: all warnings being treated as errors
make[1]: *** [objs/Makefile:1485: objs/addon/src/ngx_srt_connection.o] Error 1
make[1]: Leaving directory './nginx'
make: *** [Makefile:10: build] Error 2
````

Anyone know howto fix? I don't see `srt_bind_acquired` being declared anywhere in the repo's.

Kind regards.

**Comment by erankor** [comment]
This function is part of libsrt (https://github.com/Haivision/srt), maybe your version is too old.

**Comment by ztjuh** [comment]
That makes sense, so I tried it again and now it still doesn't complete the compile... 

```
/usr/bin/ld: objs/addon/src/ngx_srt_connection.o: in function `ngx_srt_listen':
/home/zkitzo/nginx-srt-module/src/ngx_srt_connection.c:1943: undefined reference to `srt_bind_acquire'
/usr/bin/ld: objs/addon/src/ngx_stream_srt_proxy_module.o: in function `ngx_stream_srt_proxy_pass':
/home/zkitzo/nginx-srt-module/src/ngx_stream_srt_proxy_module.c:621: undefined reference to `ngx_stream_core_module'
/usr/bin/ld: objs/addon/src/ngx_stream_srt_proxy_module.o: in function `ngx_stream_srt_proxy_cleanup':
/home/zkitzo/nginx-srt-module/src/ngx_stream_srt_proxy_module.c:528: undefined reference to `ngx_stream_finalize_session'
/usr/bin/ld: objs/addon/src/ngx_stream_srt_proxy_module.o: in function `ngx_stream_srt_proxy_handler':
/home/zkitzo/nginx-srt-module/src/ngx_stream_srt_proxy_module.c:139: undefined reference to `ngx_stream_complex_value'
/usr/bin/ld: /home/zkitzo/nginx-srt-module/src/ngx_stream_srt_proxy_module.c:142: undefined reference to `ngx_stream_finalize_session'
/usr/bin/ld: /home/zkitzo/nginx-srt-module/src/ngx_stream_srt_proxy_module.c:151: undefined reference to `ngx_stream_complex_value'
/usr/bin/ld: /home/zkitzo/nginx-srt-module/src/ngx_stream_srt_proxy_module.c:154: undefined reference to `ngx_stream_finalize_session'
/usr/bin/ld: /home/zkitzo/nginx-srt-module/src/ngx_stream_srt_proxy_module.c:167: undefined reference to `ngx_stream_finalize_session'
/usr/bin/ld: /home/zkitzo/nginx-srt-module/src/ngx_stream_srt_proxy_module.c:174: undefined reference to `ngx_stream_finalize_session'
/usr/bin/ld: objs/addon/src/ngx_stream_srt_proxy_module.o:(.data.rel+0xf8): undefined reference to `ngx_stream_set_complex_value_slot'
/usr/bin/ld: objs/addon/src/ngx_stream_srt_proxy_module.o:(.data.rel+0x130): undefined reference to `ngx_stream_set_complex_value_slot'
/usr/bin/ld: objs/addon/src/ngx_stream_preread_str_module.o: in function `ngx_stream_preread_str_preread_init':
/home/zkitzo/nginx-srt-module/src/ngx_stream_preread_str_module.c:218: undefined reference to `ngx_stream_core_module'
/usr/bin/ld: objs/addon/src/ngx_stream_preread_str_module.o: in function `ngx_stream_preread_str_add_variables':
/home/zkitzo/nginx-srt-module/src/ngx_stream_preread_str_module.c:170: undefined reference to `ngx_stream_add_variable'
collect2: error: ld returned 1 exit status
make[1]: *** [objs/Makefile:302: objs/nginx] Error 1
make[1]: Leaving directory '/home/zkitzo/nginx'
make: *** [Makefile:10: build] Error 2
```

**Comment by erankor** [comment]
This module requires the nginx 'stream' module - add `--with-stream` to the nginx configure command.

**Comment by ztjuh** [comment]
It's in there..

**Comment by ztjuh** [comment]
I am using `--add-module` as well.. The latest output is:

```
/usr/bin/ld: objs/addon/src/ngx_srt_connection.o: in function `ngx_srt_listen':
ngx_srt_connection.c:(.text+0x427b): undefined reference to `srt_bind_acquire'
/usr/bin/ld: objs/addon/src/ngx_stream_srt_proxy_module.o: in function `ngx_stream_srt_proxy_handler':
ngx_stream_srt_proxy_module.c:(.text+0x2dc): undefined reference to `ngx_stream_complex_value'
/usr/bin/ld: ngx_stream_srt_proxy_module.c:(.text+0x2f5): undefined reference to `ngx_stream_finalize_session'
/usr/bin/ld: ngx_stream_srt_proxy_module.c:(.text+0x333): undefined reference to `ngx_stream_complex_value'
/usr/bin/ld: ngx_stream_srt_proxy_module.c:(.text+0x34c): undefined reference to `ngx_stream_finalize_session'
/usr/bin/ld: ngx_stream_srt_proxy_module.c:(.text+0x3c5): undefined reference to `ngx_stream_finalize_session'
/usr/bin/ld: ngx_stream_srt_proxy_module.c:(.text+0x413): undefined reference to `ngx_stream_finalize_session'
/usr/bin/ld: objs/addon/src/ngx_stream_srt_proxy_module.o: in function `ngx_stream_srt_proxy_cleanup':
ngx_stream_srt_proxy_module.c:(.text+0x11a3): undefined reference to `ngx_stream_finalize_session'
/usr/bin/ld: objs/addon/src/ngx_stream_srt_proxy_module.o: in function `ngx_stream_srt_proxy_pass':
ngx_stream_srt_proxy_module.c:(.text+0x1468): undefined reference to `ngx_stream_core_module'
/usr/bin/ld: objs/addon/src/ngx_stream_srt_proxy_module.o:(.data.rel+0xf8): undefined reference to `ngx_stream_set_complex_value_slot'
/usr/bin/ld: objs/addon/src/ngx_stream_srt_proxy_module.o:(.data.rel+0x130): undefined reference to `ngx_stream_set_complex_value_slot'
/usr/bin/ld: objs/addon/src/ngx_stream_preread_str_module.o: in function `ngx_stream_preread_str_add_variables':
ngx_stream_preread_str_module.c:(.text+0x341): undefined reference to `ngx_stream_add_variable'
/usr/bin/ld: objs/addon/src/ngx_stream_preread_str_module.o: in function `ngx_stream_preread_str_preread_init':
ngx_stream_preread_str_module.c:(.text+0x46b): undefined reference to `ngx_stream_core_module'
collect2: error: ld returned 1 exit status
make[1]: *** [objs/Makefile:302: objs/nginx] Error 1
make[1]: Leaving directory '/home/zkitzo/nginx'
make: *** [Makefile:10: build] Error 2
```

I have downloaded the lastest srt by `gh repo clone Haivision/srt` compiled it and installed it but I think the reference is to the source code and I don't know how to link this..

**Comment by ztjuh** [comment]
After drinking a 2 beers I misread the readme and needed `add-dynamic-module` instead of `add-module`. 🤦🏻‍♂️
